{{- if and .Values.config.admin .Values.config.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lana.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "lana.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: {{ .Values.config.admin.port }}
      protocol: TCP
      targetPort: admin
  selector: {{- include "lana.selectorLabels" . | nindent 4 }}
{{- end }}
